import { Product, Category } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Miel de Thym Sauvage',
    category: Category.HONEY,
    price: 35.000,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=400&fit=crop',
    description: 'Miel de thym pur récolté dans les montagnes de Zaghouan. Une couleur ambrée et un arôme puissant caractère ce miel d\'exception.',
    producer: 'Rucher de Zaghouan',
    benefits: ['Cicatrisant puissant', 'Antiseptique naturel', 'Apaise la toux'],
    ingredients: ['100% Miel de Thym'],
    isOrganic: true,
    isArtisanal: true,
    rating: 4.9,
    reviews: 89
  },
  {
    id: '2',
    name: 'Miel de Romarin',
    category: Category.HONEY,
    price: 28.000,
    image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400&h=400&fit=crop',
    description: 'Miel de romarin délicat et floral, récolté dans les collines du Cap Bon. Sa texture crémeuse et sa saveur douce en font un miel de table idéale.',
    producer: 'Api-Culture Nabeul',
    benefits: ['Santé hépatique', 'Antioxidant', 'Digestif'],
    ingredients: ['100% Miel de Romarin'],
    isOrganic: false,
    isArtisanal: true,
    rating: 4.7,
    reviews: 56
  },
  {
    id: '3',
    name: 'Propolis Brute',
    category: Category.DERIVATIVES,
    price: 45.000,
    image: 'https://images.unsplash.com/photo-1606811842268-ab44625c7d2e?w=400&h=400&fit=crop',
    description: 'Propolis pure récoltée par nos apiculteurs. Puissant antiviral et antibactérien naturel. Utilisée depuis des siècles pour renforcer l\'immunité.',
    producer: 'Rucher de Zaghouan',
    benefits: ['Renforce l\'immunité', 'Antiviral naturel', 'Anti-inflammatoire'],
    ingredients: ['100% Propolis brute'],
    isOrganic: true,
    isArtisanal: true,
    rating: 4.8,
    reviews: 42
  },
  {
    id: '4',
    name: 'Gélule de Gelée Royale',
    category: Category.DERIVATIVES,
    price: 55.000,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop',
    description: 'Gélules de gelée royale fraîche, lyophilisée pour préserver tous ses nutriments. La reine des produits de la ruche.',
    producer: 'Api-Culture Tunis',
    benefits: ['Vitalité & énergie', 'Anti-âge', 'Système immunitaire'],
    ingredients: ['Gelée royale lyophilisée', 'Enveloppe végétale'],
    isOrganic: false,
    isArtisanal: true,
    rating: 4.9,
    reviews: 34
  },
  {
    id: '5',
    name: 'Pollen de Fleurs Sauvages',
    category: Category.DERIVATIVES,
    price: 22.000,
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=400&fit=crop',
    description: 'Pollen récolté sur fleurs sauvages du Sahel tunisien. Riches en protéines, vitamines et acides aminés essentiels.',
    producer: 'Rucher du Sahel',
    benefits: ['Riche en protéines', 'Boost d\'énergie', 'Fertilité'],
    ingredients: ['100% Pollen de fleurs sauvages'],
    isOrganic: true,
    isArtisanal: true,
    rating: 4.6,
    reviews: 67
  },
  {
    id: '6',
    name: 'Hydromel Artisanal',
    category: Category.DERIVATIVES,
    price: 38.000,
    image: 'https://images.unsplash.com/photo-1516550893923-42d7a379cead?w=400&h=400&fit=crop',
    description: 'Hydromel préparé traditionnellement avec du miel de thym et de l\'eau de source. Fermentation naturelle, sans additifs.',
    producer: 'Rucher de Zaghouan',
    benefits: ['Antioxydant naturel', 'Sommeil réparateur', 'Digestif'],
    ingredients: ['Miel de thym', 'Eau de source', 'Levures naturelles'],
    isOrganic: true,
    isArtisanal: true,
    rating: 4.8,
    reviews: 23
  },
  {
    id: '7',
    name: 'Miel de Caroubier',
    category: Category.HONEY,
    price: 30.000,
    image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400&h=400&fit=crop',
    description: 'Miel de caroubier rare et foncé, au goût puissant et caramelisé. Récolté dans les régions du sud tunisien.',
    producer: 'Apiculture du Sud',
    benefits: ['Énergie longue durée', 'Magnésium & fer', 'Reconstituant'],
    ingredients: ['100% Miel de Caroubier'],
    isOrganic: false,
    isArtisanal: true,
    rating: 4.7,
    reviews: 38
  },
  {
    id: '8',
    name: 'Bonbons au Miel & Propolis',
    category: Category.DERIVATIVES,
    price: 15.000,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=400&fit=crop',
    description: 'Bonbons naturels à sucer : miel de thym, propolis et huile essentielle de pin. Soulagement naturel de la gorge.',
    producer: 'Rahiq Store',
    benefits: ['Soulage la gorge', 'Antiseptique buccal', '100% naturel'],
    ingredients: ['Miel de thym', 'Propolis', 'Huile essentielle de pin'],
    isOrganic: true,
    isArtisanal: true,
    rating: 4.5,
    reviews: 91
  },
  {
    id: '9',
    name: 'Cire d\'Abeille pure',
    category: Category.DERIVATIVES,
    price: 18.000,
    image: 'https://images.unsplash.com/photo-1606811842268-ab44625c7d2e?w=400&h=400&fit=crop',
    description: 'Cire d\'abeille pure, jaune naturel, pour cosmétiques naturels et soins de la peau. Sans traitement chimique.',
    producer: 'Rucher de Zaghouan',
    benefits: ['Hydratation peau', 'Baume naturel', 'Cire pour bougies'],
    ingredients: ['100% Cire d\'abeille naturelle'],
    isOrganic: false,
    isArtisanal: true,
    rating: 4.6,
    reviews: 29
  },
  {
    id: '10',
    name: 'Miel de Djebba (Bio)',
    category: Category.HONEY,
    price: 42.000,
    image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400&h=400&fit=crop',
    description: 'Miel de Djebba, région montagneuse du nord-ouest tunisien. Miel multifloral de haute montagne, certification BIO.',
    producer: 'Coopérative Djebba',
    benefits: ['Terroir unique', 'Polyfloral BIO', 'Saveurs de montagne'],
    ingredients: ['100% Miel de Djebba'],
    isOrganic: true,
    isArtisanal: true,
    rating: 5.0,
    reviews: 15
  }
];

export const CATEGORIES = Object.values(Category);